# .github/workflows/deploy-book.yml
name: Build & Deploy Book

on:
  push:
    branches: [ main ]

permissions:
  contents: write         # for pushing to gh-pages
  pages: write            # for GitHub Pages
  id-token: write         # for OIDC-based authentication if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0    # needed for gh-pages pushes

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install jupyter-book myst-nb sphinx-book-theme

      - name: Build the book
        run: jupyter-book build .

      # --- Deploy to GitHub Pages via gh-pages branch ---
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html
          publish_branch: gh-pages
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
